# Generated by Django 2.1.4 on 2018-12-20 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181220_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('C', 'Current_Account'), ('S', 'Saving_Account')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='mob',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
