# Generated by Django 2.1.4 on 2018-12-25 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(500)]),
        ),
    ]
