# Generated by Django 2.1.4 on 2018-12-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181225_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='Reciever',
            new_name='reciever',
        ),
    ]
