# Generated by Django 2.1.4 on 2018-12-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20181225_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
