# Generated by Django 2.1.4 on 2019-01-11 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181225_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='B_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(0)])),
                ('email', models.CharField(max_length=256, null=True, unique=True, validators=[django.core.validators.EmailValidator])),
                ('password', models.CharField(default='123456', max_length=10)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('mob', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(10)])),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
