# Generated by Django 2.1.4 on 2019-01-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_b_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='B_User',
            new_name='Employee',
        ),
    ]
