# Generated by Django 2.1.4 on 2019-01-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190111_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='age',
            new_name='age_emp',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='email_emp',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='name_emp',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='password',
            new_name='password_emp',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
